### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by akashdeep-singh** [akio/rosgo#11]
I don't see work on PRs and issues, the documentation seems outdated, the examples don't compile. Is someone working on it or there's a replacement for a ROS library for go?

**Comment by NickQian** [comment]
ros in golang is such a good idea. Hope @akio could go further on this. 
at least the catkin can be supported.

**Comment by maxiride** [comment]
Totally following this, if anyone finds replacements or good advanced forks let us know!

**Comment by akio** [comment]
After a long break, I'm now back and refresh the project to be more Go friendly.
Thank you for your comments and feedbacks.
